import { IPlayer, CultivationRealm } from '../entities/Player';
import { WorldId } from '../entities/WorldDefinition';
import { ZoneBlueprintDB } from '../../data/blueprints/BlueprintDB';
import { SEED_TECHNIQUES, getTechniqueById } from '../../data/seed/techniques';
import { SEED_ITEMS, getItemById } from '../../data/seed/items';
import { getTalentEffects } from '../../data/talents/talent_data';
import { getMethod } from '../../data/methods/method_data';

export type OriginType = string;

export interface IOriginConfig {
  type: OriginType;
  name: string;
  description: string;
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
  /** 所属世界 */
  worldId: WorldId;
  startingRealm: CultivationRealm;
  startingStage: number;
  startingGold: [number, number];
  startingItems: string[];
  startingTechniques: string[];
  startingMethodId?: string;
  startingTalentCount: number;
  possibleZones: string[];
  socialConnections: string[];
  questCategories: string[];
  /** 出身社会职位/身份 */
  startingPosition: string;
  /** 起始房间ID（指定具体出生房间，不指定则自动选择） */
  startingRoomId?: string;
}

export interface IOriginResult {
  config: IOriginConfig;
  zoneId: string;
  roomId: string;
  zoneName: string;
  roomName: string;
  originName: string;
  originDescription: string;
}

const ORIGIN_CONFIGS: IOriginConfig[] = [
  {
    type: 'huang_village_orphan',
    name: '荒村孤儿',
    description: '你是荒村的一名孤儿，从小在村中祠堂长大。村里的老人教你认字、种地，虽然日子清苦，但也算安稳。',
    rarity: 'common',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 1,
    startingGold: [0, 5],
    startingItems: ['copper_coin', 'farming_hoe'],
    startingTechniques: [],
    startingTalentCount: 0,
    possibleZones: ['stone_village', 'wasteland', 'stone_country_village'],
    socialConnections: ['village_elder', 'foster_parent'],
    questCategories: ['errand', 'gathering', 'protection'],
    startingPosition: '村中孤儿',
  },
  {
    type: 'stone_village_child',
    name: '青云村孩童',
    description: '你出生在青云村，父母都是淳朴的村民。村里的祭台祭司偶尔会教孩子们一些粗浅的锻体法门。',
    rarity: 'common',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 1,
    startingGold: [3, 15],
    startingItems: ['stone_flint', 'healing_herb'],
    startingTechniques: ['basic_body'],
    startingTalentCount: 0,
    possibleZones: ['stone_village', 'stone_country_village'],
    socialConnections: ['village_elder', 'clan_priest'],
    questCategories: ['errand', 'hunting', 'gathering'],
    startingPosition: '青云村村民',
    startingRoomId: 'stone_village_houses',
  },
  {
    type: 'wasteland_hunters',
    name: '蛮荒猎户',
    description: '你从小在蛮荒之地长大，跟着父辈学习狩猎。你的箭术不错，对这片土地了如指掌。',
    rarity: 'common',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 2,
    startingGold: [5, 20],
    startingItems: ['hunting_bow', 'iron_arrow_x10'],
    startingTechniques: ['basic_archery'],
    startingTalentCount: 1,
    possibleZones: ['wasteland', 'hundred_breaks', 'wind_country_village'],
    socialConnections: ['hunter', 'village_elder'],
    questCategories: ['hunting', 'scouting', 'protection'],
    startingPosition: '蛮荒猎户',
  },
  {
    type: 'blacksmith_apprentice',
    name: '铁匠学徒',
    description: '你是镇上铁匠铺的学徒，从小跟着师父学习打铁。虽然修炼天赋一般，但臂力惊人。',
    rarity: 'common',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 2,
    startingGold: [5, 25],
    startingItems: ['hammer', 'iron_ore'],
    startingTechniques: ['forging_body'],
    startingTalentCount: 1,
    possibleZones: ['stone_city', 'golden_wolf'],
    socialConnections: ['blacksmith', 'shopkeeper'],
    questCategories: ['craft', 'errand', 'trade'],
    startingPosition: '铁匠学徒',
    startingRoomId: 'stone_city_blacksmith',
  },
  {
    type: 'herbalist_child',
    name: '采药童',
    description: '你跟着爷爷在山中采药为生。爷爷是个隐世的老药师，教了你不少辨认草药的本事。',
    rarity: 'common',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 2,
    startingGold: [3, 15],
    startingItems: ['herbal_bag', 'healing_herb_x3'],
    startingTechniques: ['herb_identification'],
    startingTalentCount: 1,
    possibleZones: ['little_gu_mountain', 'immortal_mountain', 'wood_country_village', 'wood_country_city', 'wood_country_capital', 'wood_country_megacity'],
    socialConnections: ['herbalist', 'mountain_guide'],
    questCategories: ['gathering', 'errand', 'healing'],
    startingPosition: '采药童',
  },
  {
    type: 'caravan_guard_child',
    name: '商队护卫之子',
    description: '你父亲是商队的护卫队长，常年走南闯北。你从小跟着商队长大，见过不少世面，也学了些防身的功夫。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 3,
    startingGold: [15, 60],
    startingItems: ['short_sword', 'traveler_cloak'],
    startingTechniques: ['basic_guard', 'survival'],
    startingTalentCount: 1,
    possibleZones: ['stone_city', 'fire_city', 'wasteland'],
    socialConnections: ['caravan_master', 'merchant'],
    questCategories: ['escort', 'trade', 'information'],
    startingPosition: '商队护卫之子',
  },
  {
    type: 'village_shaman_apprentice',
    name: '巫医学徒',
    description: '你是部落巫师的学徒，学习草药和祭祀之术。你能与祖先沟通，知晓一些古老的秘密。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 3,
    startingGold: [10, 40],
    startingItems: ['shaman_staff', 'spirit_powder'],
    startingTechniques: ['spirit_commune', 'healing'],
    startingTalentCount: 1,
    possibleZones: ['stone_village', 'blood_god'],
    socialConnections: ['shaman', 'tribal_leader'],
    questCategories: ['ritual', 'healing', 'protection'],
    startingPosition: '巫医学徒',
  },
  {
    type: 'scholar_family',
    name: '书香门第',
    description: '你出生在一个读书人家，从小饱读诗书。虽然不会修炼，但你学识渊博，对天下大势了如指掌。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 3,
    startingGold: [20, 80],
    startingItems: ['ancient_book', 'ink_stone'],
    startingTechniques: ['knowledge'],
    startingTalentCount: 1,
    possibleZones: ['stone_city', 'zhulu_shuyuan', 'human_country_village', 'human_country_city', 'human_country_capital', 'human_country_megacity'],
    socialConnections: ['scholar', 'teacher'],
    questCategories: ['information', 'diplomatic', 'research'],
    startingPosition: '书香子弟',
    startingRoomId: 'stone_city_bookstore',
  },
  {
    type: 'disgraced_cultivator_child',
    name: '落魄修士后代',
    description: '你的父亲曾经是一名修士，因故被废修为。他将毕生所学传授于你，希望你能重振家门。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 4,
    startingGold: [30, 100],
    startingItems: ['broken_sword', 'cultivation_notes'],
    startingTechniques: ['basic_cultivation'],
    startingMethodId: 'yuanshi_zhenjie',
    startingTalentCount: 1,
    possibleZones: ['stone_city', 'fire_city'],
    socialConnections: ['ex_cultivator', 'herbalist'],
    questCategories: ['revenge', 'treasure', 'protection'],
    startingPosition: '落魄修士之后',
  },
  {
    type: 'merchant_apprentice',
    name: '商行学徒',
    description: '你是城中大商行的学徒，精明能干，善于经商。虽然不会武功，但你懂得人情世故。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 3,
    startingGold: [25, 100],
    startingItems: ['account_book', 'small_bag'],
    startingTechniques: ['negotiation'],
    startingTalentCount: 1,
    possibleZones: ['stone_city', 'fire_city'],
    socialConnections: ['merchant', 'shopkeeper'],
    questCategories: ['trade', 'information', 'errand'],
    startingPosition: '商行学徒',
    startingRoomId: 'stone_city_market',
  },
  {
    type: 'city_guard_recruit',
    name: '城防新兵',
    description: '你被招募为城防军的一员，接受正规的军事训练。虽然只是普通士兵，但也算有个正经差事。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 4,
    startingGold: [20, 60],
    startingItems: ['iron_spear', 'guard_armor'],
    startingTechniques: ['basic_spear', 'formation_fight'],
    startingTalentCount: 1,
    possibleZones: ['stone_city', 'fire_city'],
    socialConnections: ['captain', 'town_guard'],
    questCategories: ['patrol', 'protection', 'escort'],
    startingPosition: '城防新兵',
    startingRoomId: 'stone_city_gate',
  },
  {
    type: 'golden_wolf_soldier',
    name: '金狼士兵',
    description: '你是金狼古国的一名普通士兵，从小接受狼图腾的熏陶。你的战力远超常人，是军中的好手。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 4,
    startingGold: [15, 50],
    startingItems: ['wolf_spear', 'wolf_armor'],
    startingTechniques: ['wolf_fighting', 'basic_body'],
    startingTalentCount: 1,
    possibleZones: ['golden_wolf'],
    socialConnections: ['wolf_general', 'wolf_soldier'],
    questCategories: ['military', 'patrol', 'hunting'],
    startingPosition: '金狼士兵',
    startingRoomId: 'wolf_plaza',
  },
  {
    type: 'qinglin_snake_keeper',
    name: '青鳞蛇夫',
    description: '你是青鳞古国的一名蛇夫，与蛇为伴。你懂得如何驯养灵蛇，也掌握了一些毒术。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 4,
    startingGold: [10, 40],
    startingItems: ['snake_charm', 'healing_herb'],
    startingTechniques: ['snake_taming', 'poison_knowledge'],
    startingTalentCount: 1,
    possibleZones: ['qinglin'],
    socialConnections: ['snake_master', 'alchemist'],
    questCategories: ['gathering', 'poison', 'protection'],
    startingPosition: '青鳞蛇夫',
  },
  {
    type: 'blood_god_cultist',
    name: '血神信徒',
    description: '你是血神古国的一名普通信徒，虔诚地信仰血神。虽然修为不高，但你的意志坚定。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 4,
    startingGold: [5, 30],
    startingItems: ['blood_amulet', 'sacrifice_knife'],
    startingTechniques: ['blood_worship', 'pain_resistance'],
    startingTalentCount: 1,
    possibleZones: ['blood_god'],
    socialConnections: ['priest', 'cultist'],
    questCategories: ['ritual', 'protection', 'hunting'],
    startingPosition: '血神信徒',
  },
  {
    type: 'fire_city_apprentice',
    name: '火城工匠',
    description: '你是火皇城的一名工匠学徒，擅长锻造和炼器。火国的锻造技艺名闻天下，你有幸学到了其中皮毛。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 4,
    startingGold: [30, 100],
    startingItems: ['fire_hammer', 'fire_essence'],
    startingTechniques: ['fire_forging', 'basic_body'],
    startingTalentCount: 1,
    possibleZones: ['fire_city', 'fire_country_village'],
    socialConnections: ['master_blacksmith', 'shopkeeper'],
    questCategories: ['craft', 'trade', 'errand'],
    startingPosition: '火城工匠学徒',
  },
  {
    type: 'stone_city_noble',
    name: '石城贵族',
    description: '你是石城的一个小贵族子弟，家族在城中有些势力。从小接受良好的教育，也修炼了一些基础功法。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 1,
    startingGold: [100, 500],
    startingItems: ['family_medallion', 'quality_sword', 'breakthrough_pill'],
    startingTechniques: ['family_art'],
    startingMethodId: 'family_method',
    startingTalentCount: 2,
    possibleZones: ['stone_city', 'stone_city_provinces', 'stone_country_city', 'stone_country_capital', 'stone_country_megacity'],
    socialConnections: ['noble_lord', 'family_elder'],
    questCategories: ['diplomatic', 'patrol', 'treasure'],
    startingPosition: '石城贵族子弟',
    startingRoomId: 'stone_city_shi_family',
  },
  {
    type: 'rain_kingdom_noble',
    name: '雨族贵胄',
    description: '你是雨王域的一名贵族，雨族虽然不如火国强大，但也是一方霸主。你的身份尊贵，资源丰富。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 1,
    startingGold: [150, 600],
    startingItems: ['rain_medallion', 'water_sword', 'spirit_pill'],
    startingTechniques: ['rain_art'],
    startingMethodId: 'rain_method',
    startingTalentCount: 2,
    possibleZones: ['rain_kingdom', 'rain_country_village', 'rain_country_city', 'rain_country_capital', 'rain_country_megacity'],
    socialConnections: ['rain_lord', 'court_official'],
    questCategories: ['diplomatic', 'military', 'treasure'],
    startingPosition: '雨族贵胄',
  },
  {
    type: 'thunder_kingdom_noble',
    name: '雷族子弟',
    description: '你是雷王域的一名雷族子弟，天生对雷电有亲和力。雷族的功法霸道无比，你从小就开始修炼。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [120, 500],
    startingItems: ['thunder_medallion', 'thunder_sword', 'thunder_pill'],
    startingTechniques: ['thunder_art'],
    startingMethodId: 'thunder_method',
    startingTalentCount: 2,
    possibleZones: ['thunder_kingdom'],
    socialConnections: ['thunder_lord', 'thunder_elder'],
    questCategories: ['military', 'trial', 'treasure'],
    startingPosition: '雷族子弟',
  },
  {
    type: 'beast_kingdom_warrior',
    name: '兽域勇士',
    description: '你是兽域的一名勇士，从小与猛兽搏斗。你的肉身强横，是天生的战士。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [80, 300],
    startingItems: ['beast_claw', 'hide_armor', 'beast_core'],
    startingTechniques: ['beast_fighting', 'body_tempering'],
    startingTalentCount: 2,
    possibleZones: ['beast_kingdom'],
    socialConnections: ['beast_lord', 'hunter'],
    questCategories: ['hunting', 'trial', 'protection'],
    startingPosition: '兽域勇士',
  },
  {
    type: 'butian_ge_discipline',
    name: '补天阁外门弟子',
    description: '你被补天阁选中，成为外门弟子。补天阁是东荒顶级势力之一，你有幸得到了正统的修炼传承。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 3,
    startingGold: [100, 400],
    startingItems: ['butian_token', 'spirit_sword', 'cultivation_pill'],
    startingTechniques: ['butian_basic', 'sword_foundation'],
    startingMethodId: 'yuanshi_zhenjie',
    startingTalentCount: 2,
    possibleZones: ['butian_ge'],
    socialConnections: ['butian_elder', 'senior_brother'],
    questCategories: ['mission', 'trial', 'treasure'],
    startingPosition: '补天阁外门弟子',
    startingRoomId: 'butian_ge_square',
  },
  {
    type: 'zhulu_shuyuan_discipline',
    name: '逐鹿书院学子',
    description: '你是逐鹿书院的一名学子，书院传承久远，培养了无数英才。你不仅学识渊博，也修炼了不错的功法。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 3,
    startingGold: [120, 500],
    startingItems: ['scholar_robe', 'writing_brush', 'knowledge_book'],
    startingTechniques: ['scholar_art', 'knowledge'],
    startingMethodId: 'scholar_method',
    startingTalentCount: 2,
    possibleZones: ['zhulu_shuyuan'],
    socialConnections: ['academy_master', 'teacher'],
    questCategories: ['research', 'diplomatic', 'protection'],
    startingPosition: '逐鹿书院学子',
    startingRoomId: 'zhulu_shuyuan_inner_court',
  },
  {
    type: 'golden_wolf_captain',
    name: '金狼百夫长',
    description: '你是金狼古国的一名百夫长，久经沙场，战功赫赫。你的指挥能力出众，是军中的中坚力量。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 3,
    startingGold: [200, 800],
    startingItems: ['wolf_captain_sword', 'wolf_armor', 'war_banner'],
    startingTechniques: ['wolf_tactics', 'wolf_fighting'],
    startingMethodId: 'wolf_method',
    startingTalentCount: 2,
    possibleZones: ['golden_wolf'],
    socialConnections: ['wolf_general', 'wolf_king'],
    questCategories: ['military', 'patrol', 'war'],
    startingPosition: '金狼百夫长',
    startingRoomId: 'wolf_palace',
  },
  {
    type: 'imperial_prince',
    name: '火国皇子',
    description: '你是火国的一名皇子，身份尊贵至极。火国是东荒霸主之一，你从小享受顶级资源和教育。',
    rarity: 'epic',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 4,
    startingGold: [500, 2000],
    startingItems: ['imperial_robes', 'fire_sword', 'spirit_pill_x3'],
    startingTechniques: ['imperial_fire', 'basic_guard'],
    startingMethodId: 'imperial_method',
    startingTalentCount: 3,
    possibleZones: ['fire_city', 'fire_city_provinces', 'fire_country_city', 'fire_country_capital', 'fire_country_megacity'],
    socialConnections: ['fire_king', 'imperial_guard', 'court_official'],
    questCategories: ['political', 'military', 'treasure'],
    startingPosition: '火国皇子',
    startingRoomId: 'fire_throne_hall',
  },
  {
    type: 'stone_kingdom_prince',
    name: '石国皇子',
    description: '你是石国的一名皇子，石国虽然不如火国强大，但也是一方大国。你从小接受帝王教育。',
    rarity: 'epic',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 4,
    startingGold: [400, 1500],
    startingItems: ['royal_robes', 'stone_sword', 'spirit_pill_x2'],
    startingTechniques: ['imperial_art', 'basic_guard'],
    startingMethodId: 'imperial_method',
    startingTalentCount: 3,
    possibleZones: ['stone_city', 'stone_kingdom'],
    socialConnections: ['stone_king', 'royal_guard', 'court_official'],
    questCategories: ['political', 'military', 'treasure'],
    startingPosition: '石国皇子',
    startingRoomId: 'stone_city_shi_family',
  },
  {
    type: 'ancient_heritage',
    name: '太古遗族',
    description: '你出生在一个传承久远的太古遗族，体内流淌着远古先民的血脉。族中珍藏着上古传承，你从小就接受最顶级的修炼指导。',
    rarity: 'epic',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 5,
    startingGold: [300, 1000],
    startingItems: ['ancient_blood_token', 'family_treasure', 'blood_pill'],
    startingTechniques: ['ancient_blood_art'],
    startingMethodId: 'ancient_method',
    startingTalentCount: 3,
    possibleZones: ['stone_village', 'hundred_breaks', 'burial_domain'],
    socialConnections: ['clan_leader', 'clan_elder'],
    questCategories: ['trial', 'guardian', 'ancient'],
    startingPosition: '太古遗族子弟',
  },
  {
    type: 'holy_land_discipline',
    name: '圣地内门弟子',
    description: '你被一座顶级圣地选中，成为内门弟子。圣地资源丰富，功法高深，但竞争也异常残酷。',
    rarity: 'epic',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 6,
    startingGold: [300, 1200],
    startingItems: ['holy_land_token', 'spiritual_sword', 'cultivation_pill_x2'],
    startingTechniques: ['holy_land_basic', 'sword_foundation'],
    startingMethodId: 'holy_land_method',
    startingTalentCount: 3,
    possibleZones: ['immortal_mountain', 'divine_garden', 'butian_ge'],
    socialConnections: ['holy_land_elder', 'senior_brother'],
    questCategories: ['mission', 'trial', 'treasure'],
    startingPosition: '圣地内门弟子',
  },
  {
    type: 'immortal_mountain_discipline',
    name: '仙山弟子',
    description: '你拜入仙山门下，仙山是东荒最神秘的势力之一。你的师父是一位隐世高人，传授了你绝世功法。',
    rarity: 'epic',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 6,
    startingGold: [250, 1000],
    startingItems: ['immortal_token', 'immortal_sword', 'immortal_pill'],
    startingTechniques: ['immortal_art', 'flight'],
    startingMethodId: 'immortal_method',
    startingTalentCount: 3,
    possibleZones: ['immortal_mountain'],
    socialConnections: ['immortal_elder', 'immortal_master'],
    questCategories: ['trial', 'guardian', 'treasure'],
    startingPosition: '仙山弟子',
    startingRoomId: 'immortal_palace',
  },
  {
    type: 'divine_garden_discipline',
    name: '神园弟子',
    description: '你是神园的一名弟子，神园孕育着无数神药和瑰宝。你从小就在灵气最浓郁的地方修炼。',
    rarity: 'epic',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 6,
    startingGold: [200, 800],
    startingItems: ['divine_token', 'divine_sword', 'divine_pill'],
    startingTechniques: ['divine_art', 'herb_identification'],
    startingMethodId: 'divine_method',
    startingTalentCount: 3,
    possibleZones: ['divine_garden'],
    socialConnections: ['divine_elder', 'gardener'],
    questCategories: ['trial', 'gathering', 'treasure'],
    startingPosition: '神园弟子',
    startingRoomId: 'divine_garden_center',
  },
  {
    type: 'ancient_king_reincarnation',
    name: '远古王者转世',
    description: '你是一位远古王者的转世之身，虽然记忆尚未觉醒，但体内封印着惊天动地的力量。',
    rarity: 'legendary',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 7,
    startingGold: [500, 2000],
    startingItems: ['king_soul_token', 'ancient_sword', 'king_pill'],
    startingTechniques: ['king_art', 'soul_perception'],
    startingMethodId: 'king_method',
    startingTalentCount: 3,
    possibleZones: ['burial_domain', 'hundred_breaks', 'immortal_mountain'],
    socialConnections: ['ancient_spirit', 'king_guardian'],
    questCategories: ['awakening', 'trial', 'ancient'],
    startingPosition: '远古王者转世',
  },
  {
    type: 'supreme_bone_owner',
    name: '天生至尊骨',
    description: '你天生拥有至尊骨，这是天地间最逆天的体质。至尊骨蕴含着无尽的潜能，是成为至尊的根基。',
    rarity: 'legendary',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 7,
    startingGold: [400, 1500],
    startingItems: ['supreme_bone_token', 'supreme_sword', 'supreme_pill'],
    startingTechniques: ['supreme_bone_art', 'body_tempering'],
    startingMethodId: 'supreme_method',
    startingTalentCount: 3,
    possibleZones: ['stone_village', 'butian_ge', 'burial_domain'],
    socialConnections: ['village_priest', 'supreme_guardian'],
    questCategories: ['trial', 'awakening', 'treasure'],
    startingPosition: '至尊骨拥有者',
  },
  {
    type: 'heavenly_immortal_body',
    name: '天生仙体',
    description: '你天生拥有仙体，是万中无一的修炼奇才。你的肉身与天地相合，修炼速度远超常人。',
    rarity: 'legendary',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 8,
    startingGold: [600, 2500],
    startingItems: ['immortal_body_token', 'immortal_sword', 'immortal_pill_x2'],
    startingTechniques: ['immortal_body_art', 'spirit_absorption'],
    startingMethodId: 'immortal_method',
    startingTalentCount: 3,
    possibleZones: ['immortal_mountain', 'divine_garden'],
    socialConnections: ['immortal_elder', 'heavenly_guardian'],
    questCategories: ['trial', 'treasure', 'awakening'],
    startingPosition: '仙体拥有者',
  },
  {
    type: 'nine_aperture_body',
    name: '九窍仙体',
    description: '你天生九窍全开，是传说中的九窍仙体。每一窍都蕴含着无尽的力量，是修炼的无上根基。',
    rarity: 'legendary',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 8,
    startingGold: [500, 2000],
    startingItems: ['nine_aperture_token', 'aperture_sword', 'aperture_pill'],
    startingTechniques: ['nine_aperture_art', 'spirit_control'],
    startingMethodId: 'nine_aperture_method',
    startingTalentCount: 3,
    possibleZones: ['divine_garden', 'butian_ge'],
    socialConnections: ['divine_elder', 'aperture_master'],
    questCategories: ['trial', 'awakening', 'treasure'],
    startingPosition: '九窍仙体拥有者',
  },
  {
    type: 'undying_body',
    name: '不灭仙体',
    description: '你拥有不灭仙体，是传说中与天同寿的体质。你的肉身坚不可摧，灵魂永不消散。',
    rarity: 'legendary',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 9,
    startingGold: [800, 3000],
    startingItems: ['undying_token', 'undying_sword', 'undying_pill'],
    startingTechniques: ['undying_art', 'immortal_regeneration'],
    startingMethodId: 'undying_method',
    startingTalentCount: 3,
    possibleZones: ['immortal_mountain', 'burial_domain'],
    socialConnections: ['undying_elder', 'immortal_guardian'],
    questCategories: ['trial', 'awakening', 'guardian'],
    startingPosition: '不灭仙体拥有者',
  },
  {
    type: 'savage_king',
    name: '荒古圣体',
    description: '你是传说中的荒古圣体，是天地间最强大的体质之一。圣体一出，万族臣服。',
    rarity: 'legendary',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 9,
    startingGold: [1000, 5000],
    startingItems: ['holy_body_token', 'holy_sword', 'holy_pill_x3'],
    startingTechniques: ['holy_body_art', 'heavenly_fist'],
    startingMethodId: 'holy_body_method',
    startingTalentCount: 3,
    possibleZones: ['stone_village', 'hundred_breaks', 'burial_domain'],
    socialConnections: ['village_priest', 'holy_guardian'],
    questCategories: ['trial', 'awakening', 'legendary'],
    startingPosition: '荒古圣体拥有者',
  },
  {
    type: 'ghost_village_child',
    name: '鬼村遗民',
    description: '你出生在鬼村，这是一个被诅咒的村落。村民们都有着一些诡异的能力，但也承受着无尽的痛苦。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 3,
    startingGold: [5, 25],
    startingItems: ['ghost_amulet', 'dark_crystal'],
    startingTechniques: ['ghost_vision', 'shadow_step'],
    startingTalentCount: 1,
    possibleZones: ['wasteland', 'burial_domain'],
    socialConnections: ['ghost_village_elder', 'ghost_walker'],
    questCategories: ['exploration', 'ritual', 'protection'],
    startingPosition: '鬼村遗民',
  },
  {
    type: 'river_tribe_child',
    name: '河伯后裔',
    description: '你是河伯部落的后裔，天生与水亲近。你的祖先曾经是一方河神，传承了控水的能力。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 4,
    startingGold: [10, 40],
    startingItems: ['river_amulet', 'water_stone'],
    startingTechniques: ['water_control', 'breath_hold'],
    startingTalentCount: 1,
    possibleZones: ['stone_village', 'blood_god'],
    socialConnections: ['river_shaman', 'fisherman'],
    questCategories: ['gathering', 'protection', 'ritual'],
    startingPosition: '河伯后裔',
  },
  {
    type: 'mountain_tribesman',
    name: '山民后裔',
    description: '你是山中部落的后裔，世代居住在深山之中。你熟悉山林的每一寸土地，也学会了与野兽沟通。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 4,
    startingGold: [8, 30],
    startingItems: ['mountain_claws', 'healing_herb'],
    startingTechniques: ['mountain_survival', 'beast_call'],
    startingTalentCount: 1,
    possibleZones: ['little_gu_mountain', 'hundred_breaks'],
    socialConnections: ['mountain_elder', 'hunter'],
    questCategories: ['hunting', 'gathering', 'scouting'],
    startingPosition: '山民后裔',
  },
  {
    type: 'desert_nomad',
    name: '荒漠行者',
    description: '你是荒漠中的游牧民族后裔，熟悉沙漠的每一条路线。你的耐力惊人，能在沙漠中生存数天。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 3,
    startingGold: [15, 50],
    startingItems: ['desert_robe', 'water_skin', 'sand_mask'],
    startingTechniques: ['desert_survival', 'sand_walk'],
    startingTalentCount: 1,
    possibleZones: ['wasteland'],
    socialConnections: ['nomad_leader', 'traveler'],
    questCategories: ['scouting', 'trade', 'escort'],
    startingPosition: '荒漠行者',
  },
  {
    type: 'sea_tribesman',
    name: '海族后裔',
    description: '你是海族的后裔，天生擅长水性。你的祖先曾经生活在大海之中，传承了一些与海洋相关的能力。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 4,
    startingGold: [12, 45],
    startingItems: ['sea_amulet', 'water_blade'],
    startingTechniques: ['water_breathing', 'ocean_sense'],
    startingTalentCount: 1,
    possibleZones: ['stone_village', 'blood_god'],
    socialConnections: ['sea_shaman', 'fisherman'],
    questCategories: ['hunting', 'gathering', 'exploration'],
    startingPosition: '海族后裔',
  },
  {
    type: 'night_people',
    name: '夜族后裔',
    description: '你是夜族的后裔，天生在夜晚行动自如。夜族是一个神秘的族群，有着不为人知的传承。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 4,
    startingGold: [10, 40],
    startingItems: ['night_cloak', 'shadow_dagger'],
    startingTechniques: ['night_vision', 'shadow_walk'],
    startingTalentCount: 1,
    possibleZones: ['wasteland', 'burial_domain'],
    socialConnections: ['night_elder', 'shadow_walker'],
    questCategories: ['scouting', 'assassination', 'exploration'],
    startingPosition: '夜族后裔',
  },
  {
    type: 'sun_people',
    name: '日族后裔',
    description: '你是日族的后裔，天生与太阳亲近。日族是一个古老的族群，传承着与太阳相关的能力。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [50, 200],
    startingItems: ['sun_amulet', 'sun_blade'],
    startingTechniques: ['sun_vision', 'heat_resistance'],
    startingTalentCount: 2,
    possibleZones: ['fire_city', 'immortal_mountain'],
    socialConnections: ['sun_elder', 'fire_cultivator'],
    questCategories: ['trial', 'protection', 'ritual'],
    startingPosition: '日族后裔',
  },
  {
    type: 'moon_people',
    name: '月族后裔',
    description: '你是月族的后裔，天生与月亮亲近。月族是一个神秘的族群，传承着与月亮相关的能力。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [50, 200],
    startingItems: ['moon_amulet', 'moon_blade'],
    startingTechniques: ['moon_vision', 'night_walk'],
    startingTalentCount: 2,
    possibleZones: ['stone_city', 'divine_garden'],
    socialConnections: ['moon_elder', 'moon_cultivator'],
    questCategories: ['trial', 'exploration', 'ritual'],
    startingPosition: '月族后裔',
  },
  {
    type: 'wind_people',
    name: '风族后裔',
    description: '你是风族的后裔，天生与风亲近。风族是一个自由的族群，传承着与风相关的能力。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [40, 150],
    startingItems: ['wind_amulet', 'wind_blade'],
    startingTechniques: ['wind_sense', 'fast_move'],
    startingTalentCount: 2,
    possibleZones: ['wasteland', 'hundred_breaks', 'wind_country_village', 'wind_country_city', 'wind_country_capital', 'wind_country_megacity'],
    socialConnections: ['wind_elder', 'wind_rider'],
    questCategories: ['scouting', 'fast_escort', 'trial'],
    startingPosition: '风族后裔',
  },
  {
    type: 'earth_people',
    name: '土族后裔',
    description: '你是土族的后裔，天生与大地亲近。土族是一个坚韧的族群，传承着与大地相关的能力。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [45, 180],
    startingItems: ['earth_amulet', 'earth_blade'],
    startingTechniques: ['earth_sense', 'stone_skin'],
    startingTalentCount: 2,
    possibleZones: ['stone_city', 'golden_wolf'],
    socialConnections: ['earth_elder', 'miner'],
    questCategories: ['mining', 'protection', 'trial'],
    startingPosition: '土族后裔',
  },
  // ===== 斗破苍穹出身 =====
  {
    type: 'doupo_xiao_family',
    name: '萧家子弟',
    description: '你是斗气大陆乌坦城萧家的一名子弟。萧家虽为小族，但也有几分底蕴。你从小修炼斗气，打下了基础。',
    rarity: 'common',
    worldId: WorldId.DOU_PO,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 1,
    startingGold: [10, 30],
    startingItems: ['douqi_pill_low', 'iron_sword'],
    startingTechniques: ['basic_douqi'],
    startingTalentCount: 0,
    possibleZones: ['doupo_wutan'],
    socialConnections: ['xiao_elder', 'family_member'],
    questCategories: ['family', 'cultivation', 'trade'],
    startingPosition: '萧家子弟',
  },
  {
    type: 'doupo_medic_apprentice',
    name: '药铺学徒',
    description: '你在乌坦城的一家药铺当学徒，跟着药师学习辨认草药和粗浅的炼药术。虽然修为一般，但懂得不少药理知识。',
    rarity: 'uncommon',
    worldId: WorldId.DOU_PO,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 2,
    startingGold: [15, 40],
    startingItems: ['herb_bag', 'basic_pill_x3'],
    startingTechniques: ['herb_identification', 'basic_alchemy'],
    startingTalentCount: 1,
    possibleZones: ['doupo_wutan'],
    socialConnections: ['pharmacist', 'shopkeeper'],
    questCategories: ['alchemy', 'gathering', 'trade'],
    startingPosition: '药铺学徒',
  },
  {
    type: 'doupo_noble_child',
    name: '贵族子弟',
    description: '你是斗气大陆某个小贵族的子弟，家族虽不大，但也有几分势力。你从小接受良好的斗气修炼教育。',
    rarity: 'rare',
    worldId: WorldId.DOU_PO,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 1,
    startingGold: [100, 300],
    startingItems: ['family_badge', 'quality_sword', 'douqi_pill_mid'],
    startingTechniques: ['family_dou_skill'],
    startingMethodId: 'basic_dou_method',
    startingTalentCount: 2,
    possibleZones: ['doupo_wutan', 'doupo_jianan'],
    socialConnections: ['noble_lord', 'family_elder'],
    questCategories: ['noble', 'cultivation', 'duel'],
    startingPosition: '贵族子弟',
  },
  // ===== 神墓出身 =====
  {
    type: 'shenmu_cemetery_keeper',
    name: '守墓人',
    description: '你是神魔陵园的一名守墓人，世代守护着这片神秘的陵园。你从小就见惯了生死，也知晓一些陵园的秘密。',
    rarity: 'common',
    worldId: WorldId.SHEN_MU,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 1,
    startingGold: [5, 15],
    startingItems: ['cemetery_key', 'old_lantern'],
    startingTechniques: ['cemetery_knowledge', 'ghost_vision'],
    startingTalentCount: 0,
    possibleZones: ['shenmu_cemetery'],
    socialConnections: ['cemetery_elder', 'grave_digger'],
    questCategories: ['exploration', 'guardian', 'ritual'],
    startingPosition: '守墓人',
  },
  {
    type: 'shenmu_taoist',
    name: '修道者',
    description: '你是一名修道者，在山中潜心修炼。你的道法有一定根基，懂得一些基础的法术和符箓之术。',
    rarity: 'uncommon',
    worldId: WorldId.SHEN_MU,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 3,
    startingGold: [20, 60],
    startingItems: ['taoist_robe', 'fu_zhuang', 'flying_sword'],
    startingTechniques: ['basic_tao_spell', 'sword_control'],
    startingTalentCount: 1,
    possibleZones: ['shenmu_cemetery', 'shenmu_mountain'],
    socialConnections: ['taoist_master', 'senior_brother'],
    questCategories: ['cultivation', 'exploration', 'exorcism'],
    startingPosition: '修道者',
  },
  {
    type: 'shenmu_god_descendant',
    name: '神祇后裔',
    description: '你体内流淌着远古神祇的血脉，虽然力量已经稀薄，但仍然有着非凡的潜力。你能感受到血脉中沉睡的力量。',
    rarity: 'rare',
    worldId: WorldId.SHEN_MU,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [80, 200],
    startingItems: ['god_blood_token', 'divine_equipment', 'spirit_pill'],
    startingTechniques: ['divine_blood_art'],
    startingMethodId: 'god_method',
    startingTalentCount: 2,
    possibleZones: ['shenmu_cemetery', 'shenmu_heaven'],
    socialConnections: ['ancient_god', 'god_guardian'],
    questCategories: ['awakening', 'trial', 'legendary'],
    startingPosition: '神祇后裔',
  },
  // ===== 凡人修仙传出身 =====
  {
    type: 'fanren_country_boy',
    name: '山村少年',
    description: '你出生在青牛镇附近的一个小山村，家境贫寒。为了改变命运，你决心踏上修仙之路，哪怕只有万分之一的机会。',
    rarity: 'common',
    worldId: WorldId.FAN_REN,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 1,
    startingGold: [0, 5],
    startingItems: ['cloth_clothes', 'dried_food'],
    startingTechniques: [],
    startingTalentCount: 0,
    possibleZones: ['fanren_qingniu'],
    socialConnections: ['village_elder', 'childhood_friend'],
    questCategories: ['survival', 'gathering', 'exploration'],
    startingPosition: '山村少年',
  },
  {
    type: 'fanren_sect_disciple',
    name: '黄枫谷外门弟子',
    description: '你有幸被黄枫谷选中，成为外门弟子。虽然只是外门，但也是正式踏入了修仙之门。你需要努力修炼才能保住地位。',
    rarity: 'uncommon',
    worldId: WorldId.FAN_REN,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 3,
    startingGold: [20, 50],
    startingItems: ['sect_robe', 'spirit_stone_x10', 'basic_pill'],
    startingTechniques: ['basic_cultivation_art'],
    startingMethodId: 'basic_cultivation_method',
    startingTalentCount: 1,
    possibleZones: ['fanren_huangfeng'],
    socialConnections: ['sect_elder', 'senior_brother'],
    questCategories: ['mission', 'cultivation', 'competition'],
    startingPosition: '黄枫谷外门弟子',
  },
  {
    type: 'fanren_casual_cultivator',
    name: '散修',
    description: '你是一名散修，没有门派依靠，独自一人在修仙界摸爬滚打。虽然资源匮乏，但你懂得如何在残酷的修仙界生存。',
    rarity: 'rare',
    worldId: WorldId.FAN_REN,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 1,
    startingGold: [50, 150],
    startingItems: ['traveler_robe', 'hidden_blade', 'spirit_stone_x30'],
    startingTechniques: ['survival_art', 'poison_resistance'],
    startingMethodId: 'scattered_cultivator_method',
    startingTalentCount: 2,
    possibleZones: ['fanren_qingniu', 'fanren_huangfeng', 'fanren_luanxing'],
    socialConnections: ['rogue_cultivator', 'merchant'],
    questCategories: ['survival', 'treasure', 'trade'],
    startingPosition: '散修',
  },
  // ===== 仙逆出身 =====
  {
    type: 'xianni_mountain_boy',
    name: '山村少年',
    description: '你是朱雀星上一个普通山村的少年，资质平庸，但心中有着逆天改命的执念。你坚信，顺为凡，逆为仙。',
    rarity: 'common',
    worldId: WorldId.XIAN_NI,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 1,
    startingGold: [0, 3],
    startingItems: ['tattered_clothes', 'wooden_sword'],
    startingTechniques: [],
    startingTalentCount: 0,
    possibleZones: ['xianni_zhuque'],
    socialConnections: ['village_elder', 'mother'],
    questCategories: ['survival', 'vengeance', 'cultivation'],
    startingPosition: '山村少年',
  },
  {
    type: 'xianni_sect_disciple',
    name: '恒岳派弟子',
    description: '你是恒岳派的一名弟子，虽然门派不大，但也是正式的修仙门派。你每天勤修苦练，渴望有朝一日能出人头地。',
    rarity: 'uncommon',
    worldId: WorldId.XIAN_NI,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 2,
    startingGold: [15, 40],
    startingItems: ['heng_yue_robe', 'spirit_stone_x5', 'qi_gathering_pill'],
    startingTechniques: ['heng_yue_basic_art'],
    startingMethodId: 'heng_yue_method',
    startingTalentCount: 1,
    possibleZones: ['xianni_zhuque', 'xianni_hengyue'],
    socialConnections: ['heng_yue_elder', 'senior_brother'],
    questCategories: ['mission', 'cultivation', 'competition'],
    startingPosition: '恒岳派弟子',
  },
  {
    type: 'xianni_reincarnation',
    name: '轮回者',
    description: '你隐约记得自己经历了不止一世。轮回的记忆在你脑海中若隐若现，虽然模糊，但给你带来了超越常人的感悟和经验。',
    rarity: 'rare',
    worldId: WorldId.XIAN_NI,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 1,
    startingGold: [30, 80],
    startingItems: ['reincarnation_jade', 'old_manual', 'spirit_stone_x20'],
    startingTechniques: ['soul_perception', 'past_life_memory'],
    startingMethodId: 'reincarnation_method',
    startingTalentCount: 2,
    possibleZones: ['xianni_zhuque', 'xianni_xiumo'],
    socialConnections: ['mysterious_old', 'soul_guide'],
    questCategories: ['awakening', 'reincarnation', 'legendary'],
    startingPosition: '轮回者',
  },
  // ===== 遮天出身 =====
  {
    type: 'zhetian_eastern_wasteland',
    name: '东荒少年',
    description: '你出生在东荒的一个偏远小城，虽然出身平凡，但体内有着神秘的体质。你渴望走出这片荒芜之地，探寻修仙之路。',
    rarity: 'common',
    worldId: WorldId.ZHE_TIAN,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 1,
    startingGold: [0, 5],
    startingItems: ['cloth_robe', 'water_bag'],
    startingTechniques: [],
    startingTalentCount: 0,
    possibleZones: ['stone_city', 'stone_village'],
    socialConnections: ['village_elder', 'town_folk'],
    questCategories: ['survival', 'exploration', 'opportunity'],
    startingPosition: '东荒少年',
  },
  {
    type: 'zhetian_ancient_clan',
    name: '荒古世家子弟',
    description: '你是荒古世家的一员，家族传承久远，拥有强大的底蕴。你从小修炼家族秘术，根基扎实，前途不可限量。',
    rarity: 'uncommon',
    worldId: WorldId.ZHE_TIAN,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 3,
    startingGold: [50, 150],
    startingItems: ['family_emblem', 'ancient_manual', 'spirit_pill_x5'],
    startingTechniques: ['family_secret_art'],
    startingMethodId: 'ancient_clan_method',
    startingTalentCount: 1,
    possibleZones: ['stone_city', 'national_capitals'],
    socialConnections: ['clan_elder', 'family_head'],
    questCategories: ['clan', 'cultivation', 'treasure'],
    startingPosition: '荒古世家子弟',
  },
  {
    type: 'zhetian_immortal_palace',
    name: '瑶池弟子',
    description: '你是瑶池圣地的弟子，仙姿绰约，天赋惊人。瑶池是东荒最顶尖的势力之一，你拥有得天独厚的修炼资源。',
    rarity: 'rare',
    worldId: WorldId.ZHE_TIAN,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 1,
    startingGold: [200, 500],
    startingItems: ['immortal_palace_robe', 'fairy_sword', 'holy_water_x3'],
    startingTechniques: ['immortal_palace_art'],
    startingMethodId: 'immortal_palace_method',
    startingTalentCount: 2,
    possibleZones: ['stone_city', 'sects'],
    socialConnections: ['palace_master', 'immortal_elder'],
    questCategories: ['sect', 'trial', 'legendary'],
    startingPosition: '瑶池弟子',
  },
  {
    type: 'zhetian_demon_clan',
    name: '妖族后裔',
    description: '你体内流淌着妖族的血脉，虽然已经淡化，但仍保留着强大的潜力。你能化为人形，在人族和妖族之间游走。',
    rarity: 'epic',
    worldId: WorldId.ZHE_TIAN,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 3,
    startingGold: [150, 400],
    startingItems: ['demon_blood_token', 'demon_core', 'shape_shift_pill'],
    startingTechniques: ['demon_transformation'],
    startingMethodId: 'demon_method',
    startingTalentCount: 3,
    possibleZones: ['wasteland', 'stone_city'],
    socialConnections: ['demon_clan', 'ancient_beast'],
    questCategories: ['awakening', 'bloodline', 'legendary'],
    startingPosition: '妖族后裔',
  },
  // ===== 圣墟出身 =====
  {
    type: 'shengxu_earth',
    name: '地球青年',
    description: '你是地球上的一名普通青年，在这个灵气枯竭的时代，你偶然获得了修炼的机缘。你必须在末世中挣扎求存，寻找进化之路。',
    rarity: 'common',
    worldId: WorldId.SHENG_XU,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 1,
    startingGold: [0, 5],
    startingItems: ['modern_clothes', 'smart_phone'],
    startingTechniques: [],
    startingTalentCount: 0,
    possibleZones: ['stone_city', 'stone_village'],
    socialConnections: ['family', 'friend'],
    questCategories: ['survival', 'evolution', 'opportunity'],
    startingPosition: '地球青年',
  },
  {
    type: 'shengxu_ruins',
    name: '遗迹守护者',
    description: '你守护着一处史前遗迹，那里埋藏着上古时代的秘密和传承。你从小就接受严格的训练，掌握了一些古老的战技。',
    rarity: 'uncommon',
    worldId: WorldId.SHENG_XU,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 2,
    startingGold: [30, 80],
    startingItems: ['guardian_armor', 'ancient_weapon', 'ruins_key'],
    startingTechniques: ['ancient_combat_art'],
    startingMethodId: 'guardian_method',
    startingTalentCount: 1,
    possibleZones: ['ruins', 'stone_city'],
    socialConnections: ['ruins_elder', 'ancient_spirit'],
    questCategories: ['guardian', 'exploration', 'treasure'],
    startingPosition: '遗迹守护者',
  },
  {
    type: 'shengxu_reincarnation',
    name: '轮回者',
    description: '你经历了无数次轮回，每一世都在追寻着某种真相。轮回的印记深深烙印在你的灵魂深处，赋予你超越常人的能力。',
    rarity: 'rare',
    worldId: WorldId.SHENG_XU,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 1,
    startingGold: [100, 300],
    startingItems: ['samsara_crystal', 'past_life_book', 'reincarnation_treasure'],
    startingTechniques: ['samsara_vision', 'karmic_insight'],
    startingMethodId: 'samsara_method',
    startingTalentCount: 2,
    possibleZones: ['stone_city', 'divine_garden'],
    socialConnections: ['samsara_lord', 'karmic_entity'],
    questCategories: ['awakening', 'reincarnation', 'legendary'],
    startingPosition: '轮回者',
  },
  {
    type: 'shengxu_celestial',
    name: '仙域遗民',
    description: '你来自破碎的仙域，是那场大战的幸存者。虽然仙域已毁，但你传承了仙域的功法和血脉，有着非凡的起点。',
    rarity: 'legendary',
    worldId: WorldId.SHENG_XU,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 5,
    startingGold: [500, 1000],
    startingItems: ['celestial_robe', 'immortal_weapon', 'celestial_pill_x10'],
    startingTechniques: ['celestial_art'],
    startingMethodId: 'celestial_method',
    startingTalentCount: 3,
    possibleZones: ['immortal_mountain', 'stone_city'],
    socialConnections: ['celestial_ancestor', 'immortal_spirit'],
    questCategories: ['revenge', 'restoration', 'legendary'],
    startingPosition: '仙域遗民',
  },
  // ===== 新增：底层凡人出身 =====
  {
    type: 'beggar_child',
    name: '乞丐孤儿',
    description: '你从小在街头流浪，靠乞讨和捡食残羹冷炙为生。虽然生活艰苦，但你学会了察言观色和在逆境中生存的本领。',
    rarity: 'common',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 1,
    startingGold: [0, 1],
    startingItems: ['tattered_bowl', 'rags'],
    startingTechniques: [],
    startingTalentCount: 0,
    possibleZones: ['stone_city', 'national_cities'],
    socialConnections: ['beggar_gang', 'street_elder'],
    questCategories: ['survival', 'thievery', 'street'],
    startingPosition: '乞丐孤儿',
    startingRoomId: 'stone_city_plaza',
  },
  {
    type: 'slave_mine_worker',
    name: '矿奴',
    description: '你被人贩子卖到了灵石矿场，日夜在黑暗的矿洞中劳作。虽然受尽折磨，但你意外发现了自己感知灵石的天赋。',
    rarity: 'common',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 1,
    startingGold: [0, 0],
    startingItems: ['mining_pick', 'rough_cloth'],
    startingTechniques: ['stone_sense'],
    startingTalentCount: 0,
    possibleZones: ['mines', 'stone_city'],
    socialConnections: ['fellow_slave', 'overseer'],
    questCategories: ['survival', 'escape', 'mining'],
    startingPosition: '矿奴',
  },
  {
    type: 'fisherman_child',
    name: '渔家子',
    description: '你出生在海边的一个小渔村，从小跟着父亲出海打渔。你熟悉潮汐和洋流，也听闻过深海中隐藏的仙岛传说。',
    rarity: 'common',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 1,
    startingGold: [2, 10],
    startingItems: ['fishing_net', 'dried_fish'],
    startingTechniques: ['water_breathing'],
    startingTalentCount: 0,
    possibleZones: ['fishing_villages', 'stone_city'],
    socialConnections: ['fisherman', 'village_elder'],
    questCategories: ['fishing', 'exploration', 'sea'],
    startingPosition: '渔家子',
  },
  {
    type: 'grave_digger',
    name: '掘墓人',
    description: '你世代以掘墓为业，在荒凉的坟场中长大。你见惯了生死，也偶然从古墓中带出一些残缺的功法和法器。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 2,
    startingGold: [5, 20],
    startingItems: ['shovel', 'grave_water', 'talisman'],
    startingTechniques: ['ghost_vision'],
    startingTalentCount: 1,
    possibleZones: ['shenmu_cemetery', 'burial_domain'],
    socialConnections: ['corpse_collector', 'ghost_talker'],
    questCategories: ['grave_robbing', 'ghost', 'exploration'],
    startingPosition: '掘墓人',
  },
  {
    type: 'merchant_caravan',
    name: '商队护卫之子',
    description: '你的父母是行走各地的商队护卫，你从小跟着商队奔波，见识过各地的风土人情，也学了一些粗浅的武艺。',
    rarity: 'common',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 1,
    startingGold: [10, 30],
    startingItems: ['travel_clothes', 'water_skin', 'iron_dagger'],
    startingTechniques: ['basic_combat'],
    startingTalentCount: 0,
    possibleZones: ['post_stations', 'national_cities'],
    socialConnections: ['caravan_leader', 'merchant'],
    questCategories: ['trade', 'escort', 'exploration'],
    startingPosition: '商队护卫之子',
  },
  // ===== 新增：势力出身 =====
  {
    type: 'royal_guard_child',
    name: '禁卫之子',
    description: '你的父亲是皇室的禁卫军，你从小在皇宫外院长大，接受过严格的武艺训练，见识过真正的强者。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 3,
    startingGold: [50, 150],
    startingItems: ['guard_uniform', 'standard_sword', 'healing_pill_x3'],
    startingTechniques: ['military_formation'],
    startingMethodId: 'royal_guard_method',
    startingTalentCount: 1,
    possibleZones: ['national_capitals', 'stone_city'],
    socialConnections: ['captain', 'prince'],
    questCategories: ['military', 'politics', 'protection'],
    startingPosition: '禁卫之子',
    startingRoomId: 'stone_city_gate',
  },
  {
    type: 'sect_inner_disciple',
    name: '补天阁内门弟子',
    description: '你是补天阁的内门弟子，天赋出众，被长老看中亲自教导。你拥有宗门提供的修炼资源和功法，起点远超常人。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [200, 500],
    startingItems: ['inner_disciple_robe', 'spirit_sword', 'cultivation_pill_x10'],
    startingTechniques: ['butian_secret_art'],
    startingMethodId: 'butian_advanced_method',
    startingTalentCount: 2,
    possibleZones: ['butian_ge', 'sects'],
    socialConnections: ['elder', 'senior_brother'],
    questCategories: ['sect', 'cultivation', 'competition'],
    startingPosition: '补天阁内门弟子',
    startingRoomId: 'butian_ge_hall',
  },
  {
    type: 'royal_prince',
    name: '石国皇子',
    description: '你是石国皇室的血脉，天生贵胄，享尽荣华富贵。你从小接受最好的教育，修炼资源源源不断，更有皇室秘传功法。',
    rarity: 'epic',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 5,
    startingGold: [1000, 3000],
    startingItems: ['dragon_robe', 'imperial_jade', 'royal_sword', 'treasure_pill_x5'],
    startingTechniques: ['imperial_dragon_art'],
    startingMethodId: 'royal_secret_method',
    startingTalentCount: 3,
    possibleZones: ['national_capitals', 'stone_city'],
    socialConnections: ['emperor', 'crown_prince'],
    questCategories: ['politics', 'power', 'legendary'],
    startingPosition: '石国皇子',
    startingRoomId: 'stone_city_shi_family',
  },
  {
    type: 'holy_land_saint',
    name: '圣地圣子',
    description: '你是某座不朽圣地的圣子，天生神体，被整个圣地倾力培养。你的未来注定辉煌，有望成为下一代大帝。',
    rarity: 'legendary',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 7,
    startingGold: [5000, 10000],
    startingItems: ['saint_robe', 'divine_weapon', 'immortal_pill_x10', 'sacred_talisman'],
    startingTechniques: ['holy_land_supreme_art'],
    startingMethodId: 'saint_supreme_method',
    startingTalentCount: 4,
    possibleZones: ['immortal_mountain', 'divine_garden'],
    socialConnections: ['holy_master', 'ancient_ancestor'],
    questCategories: ['legendary', 'heir', 'supreme'],
    startingPosition: '圣地圣子',
    startingRoomId: 'immortal_palace',
  },
  {
    type: 'beast_tamer_child',
    name: '驯兽师后裔',
    description: '你出生在一个以驯养凶兽为生的家族，从小与各种猛兽为伴。你懂得与野兽沟通的方法，也能借助兽血强化自身。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 2,
    startingGold: [30, 80],
    startingItems: ['beast_whip', 'taming_pill', 'blood_contract'],
    startingTechniques: ['beast_language'],
    startingMethodId: 'beast_taming_method',
    startingTalentCount: 1,
    possibleZones: ['beast_kingdom', 'camps'],
    socialConnections: ['beast_master', 'spirit_beast'],
    questCategories: ['beast', 'taming', 'exploration'],
    startingPosition: '驯兽师后裔',
  },
  // ===== 新增：禁地与特殊区域出身 =====
  {
    type: 'forbidden_land_survivor',
    name: '禁地幸存者',
    description: '你曾误入一处生命禁区，却奇迹般生还。虽然身体受到了诡异力量的侵蚀，但你也获得了常人难以想象的能力。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 3,
    startingGold: [100, 300],
    startingItems: ['cursed_amulet', 'forbidden_water', 'ancient_map'],
    startingTechniques: ['curse_resistance', 'dark_vision'],
    startingMethodId: 'forbidden_method',
    startingTalentCount: 2,
    possibleZones: ['burial_domain', 'ruins'],
    socialConnections: ['cursed_one', 'mysterious_guide'],
    questCategories: ['forbidden', 'survival', 'curse'],
    startingPosition: '禁地幸存者',
  },
  {
    type: 'ancient_ruin_dweller',
    name: '遗迹遗民',
    description: '你的祖先是一群躲避战乱的修士，他们躲进了一处远古遗迹并世代居住其中。你继承了祖先的部分传承，对外界知之甚少。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 3,
    startingGold: [50, 150],
    startingItems: ['ancient_relic', 'ruin_key', 'old_manual'],
    startingTechniques: ['ancient_rune_reading'],
    startingMethodId: 'ruin_heritage_method',
    startingTalentCount: 1,
    possibleZones: ['ruins', 'ancient_ruins'],
    socialConnections: ['ruin_elder', 'ancestor_spirit'],
    questCategories: ['heritage', 'exploration', 'ancient'],
    startingPosition: '遗迹遗民',
  },
  {
    type: 'demon_cave_inhabitant',
    name: '魔窟住民',
    description: '你出生在魔道势力的领地，从小耳濡目染的都是弱肉强食的法则。你修炼魔功，行事不择手段，但内心深处仍保留着一丝人性。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [80, 200],
    startingItems: ['demon_robe', 'blood_pill', 'soul_jar'],
    startingTechniques: ['blood_demon_art'],
    startingMethodId: 'demon_cultivation_method',
    startingTalentCount: 2,
    possibleZones: ['blood_god', 'burial_domain'],
    socialConnections: ['demon_lord', 'fellow_cultivator'],
    questCategories: ['demon', 'power', 'survival'],
    startingPosition: '魔窟住民',
  },
  {
    type: 'spirit_root_guardian',
    name: '灵根守护者',
    description: '你守护着一株万年灵根，世代相传。灵根的灵气滋养了你的体质，让你拥有超乎常人的修炼天赋。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [100, 250],
    startingItems: ['spirit_root_branch', 'life_water', 'nature_robe'],
    startingTechniques: ['nature_communion'],
    startingMethodId: 'spirit_root_method',
    startingTalentCount: 2,
    possibleZones: ['divine_garden', 'immortal_mountain'],
    socialConnections: ['nature_spirit', 'tree_elder'],
    questCategories: ['nature', 'guardian', 'cultivation'],
    startingPosition: '灵根守护者',
  },
  {
    type: 'battlefield_orphan',
    name: '战场孤儿',
    description: '你出生在一片古战场上，父母死于修士的战争。你在尸骨和残骸中长大，被战争的煞气侵蚀，却也获得了惊人的战斗本能。',
    rarity: 'uncommon',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 2,
    startingGold: [5, 20],
    startingItems: ['broken_sword', 'war_trophy', 'blood_stained_cloth'],
    startingTechniques: ['battle_intuition'],
    startingMethodId: 'war_path_method',
    startingTalentCount: 1,
    possibleZones: ['battlefields', 'wasteland'],
    socialConnections: ['war_veteran', 'mercenary'],
    questCategories: ['war', 'survival', 'revenge'],
    startingPosition: '战场孤儿',
  },
  // ===== 新增：特殊体质出身 =====
  {
    type: 'chaos_body',
    name: '混沌体',
    description: '你天生混沌体，体内蕴含着开天辟地之初的混沌之气。这种体质万古罕见，一旦大成可混沌加身，万法不侵。',
    rarity: 'legendary',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 5,
    startingGold: [3000, 8000],
    startingItems: ['chaos_stone', 'primordial_pill', 'void_robe'],
    startingTechniques: ['chaos_art'],
    startingMethodId: 'chaos_supreme_method',
    startingTalentCount: 4,
    possibleZones: ['stone_city', 'immortal_mountain'],
    socialConnections: ['chaos_ancestor', 'heavenly_master'],
    questCategories: ['legendary', 'body', 'supreme'],
    startingPosition: '混沌体拥有者',
  },
  {
    type: 'pangu_body',
    name: '霸体',
    description: '你拥有传说中的霸体，肉身强横无匹，力大无穷。霸体大成后可肉身成圣，一拳碎星辰，一脚裂大地。',
    rarity: 'epic',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 4,
    startingGold: [800, 2000],
    startingItems: ['strength_stone', 'body_tempering_pill', 'heavy_armor'],
    startingTechniques: ['body_supremacy'],
    startingMethodId: 'body_saint_method',
    startingTalentCount: 3,
    possibleZones: ['wasteland', 'stone_city'],
    socialConnections: ['body_cultivator', 'martial_saint'],
    questCategories: ['body', 'strength', 'battle'],
    startingPosition: '霸体拥有者',
  },
  {
    type: 'yin_yang_body',
    name: '阴阳体',
    description: '你天生阴阳调和，可同时修炼阴阳两种相克的功法。这种体质极为特殊，修炼到高深处可演化太极，掌控生死。',
    rarity: 'epic',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 3,
    startingGold: [500, 1500],
    startingItems: ['yin_yang_jade', 'tai_chi_manual', 'dual_robe'],
    startingTechniques: ['yin_yang_balance'],
    startingMethodId: 'yin_yang_method',
    startingTalentCount: 3,
    possibleZones: ['stone_city', 'national_capitals'],
    socialConnections: ['dual_cultivator', 'tao_master'],
    questCategories: ['balance', 'dual', 'mystic'],
    startingPosition: '阴阳体拥有者',
  },
  {
    type: 'sword_heart_body',
    name: '剑心通明',
    description: '你天生剑心通明，对剑道有着超乎常人的领悟力。任何剑法在你面前都能迅速学会，你的剑意可斩破虚妄。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [150, 400],
    startingItems: ['spirit_sword', 'sword_manual', 'sword_heart_stone'],
    startingTechniques: ['sword_intuition'],
    startingMethodId: 'sword_heart_method',
    startingTalentCount: 2,
    possibleZones: ['stone_city', 'sects'],
    socialConnections: ['sword_saint', 'blade_master'],
    questCategories: ['sword', 'combat', 'enlightenment'],
    startingPosition: '剑心通明者',
  },
  {
    type: 'poison_body',
    name: '万毒体',
    description: '你天生万毒不侵，体内可孕育剧毒。这种体质让你成为毒道的天才，但也让你在世俗中备受排挤。',
    rarity: 'rare',
    worldId: WorldId.PERFECT_WORLD,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [100, 300],
    startingItems: ['poison_jar', 'antidote_pill', 'venomous_spider'],
    startingTechniques: ['poison_mastery'],
    startingMethodId: 'ten_thousand_poison_method',
    startingTalentCount: 2,
    possibleZones: ['qinglin', 'wasteland'],
    socialConnections: ['poison_master', 'hermit'],
    questCategories: ['poison', 'survival', 'forbidden'],
    startingPosition: '万毒体拥有者',
  },
  // ===== 新增：其他小说世界出身 =====
  {
    type: 'fanren_pill_apprentice',
    name: '丹阁学徒',
    description: '你在黄枫谷的丹阁当学徒，虽然修为不高，但对炼丹有着独特的悟性。你梦想着有朝一日能炼制出传说中的仙丹。',
    rarity: 'uncommon',
    worldId: WorldId.FAN_REN,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 2,
    startingGold: [30, 80],
    startingItems: ['pill_furnace', 'herb_bag', 'basic_pill_manual'],
    startingTechniques: ['herb_identification'],
    startingMethodId: 'basic_alchemy_method',
    startingTalentCount: 1,
    possibleZones: ['fanren_huangfeng', 'fanren_qingniu'],
    socialConnections: ['pill_master', 'fellow_apprentice'],
    questCategories: ['alchemy', 'gathering', 'craft'],
    startingPosition: '丹阁学徒',
  },
  {
    type: 'fanren_beast_tamer',
    name: '御兽山弟子',
    description: '你是御兽山的外门弟子，擅长驯养各种灵兽。你与一只灵兽建立了深厚的羁绊，它是你最忠实的伙伴。',
    rarity: 'rare',
    worldId: WorldId.FAN_REN,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 1,
    startingGold: [80, 200],
    startingItems: ['spirit_pet_egg', 'beast_food', 'taming_whip'],
    startingTechniques: ['beast_control'],
    startingMethodId: 'beast_taming_method',
    startingTalentCount: 2,
    possibleZones: ['fanren_huangfeng', 'fanren_luanxing'],
    socialConnections: ['beast_master', 'spirit_pet'],
    questCategories: ['beast', 'exploration', 'companionship'],
    startingPosition: '御兽山外门弟子',
  },
  {
    type: 'xianni_demon_cultivator',
    name: '修魔海散修',
    description: '你是修魔海的一名散修，在弱肉强食的修魔海中艰难求生。你行事狠辣，不择手段，只为在这残酷的世界中活下去。',
    rarity: 'uncommon',
    worldId: WorldId.XIAN_NI,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 2,
    startingGold: [40, 100],
    startingItems: ['demon_sea_token', 'blood_dagger', 'poison_pill'],
    startingTechniques: ['demon_sea_art'],
    startingMethodId: 'demon_sea_method',
    startingTalentCount: 1,
    possibleZones: ['xianni_xiumo', 'xianni_zhuque'],
    socialConnections: ['demon_cultivator', 'sea_bandit'],
    questCategories: ['survival', 'demon', 'sea'],
    startingPosition: '修魔海散修',
  },
  {
    type: 'xianni_alchemist',
    name: '丹鼎门弟子',
    description: '你是丹鼎门的弟子，专修炼丹之术。你对各种灵草和丹方了如指掌，是门派中冉冉升起的炼丹新星。',
    rarity: 'rare',
    worldId: WorldId.XIAN_NI,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 1,
    startingGold: [100, 300],
    startingItems: ['alchemy_furnace', 'spirit_herb_collection', 'dan_formula'],
    startingTechniques: ['alchemy_mastery'],
    startingMethodId: 'dan_ding_method',
    startingTalentCount: 2,
    possibleZones: ['xianni_zhuque', 'xianni_hengyue'],
    socialConnections: ['dan_master', 'fellow_disciple'],
    questCategories: ['alchemy', 'cultivation', 'craft'],
    startingPosition: '丹鼎门弟子',
  },
  {
    type: 'zhetian_ancient_mine',
    name: '古矿奴',
    description: '你被卖到东荒的古老矿场挖矿，却意外挖出了一块神源。神源的力量改变了你的体质，让你拥有了修炼的可能。',
    rarity: 'uncommon',
    worldId: WorldId.ZHE_TIAN,
    startingRealm: CultivationRealm.MORTAL,
    startingStage: 2,
    startingGold: [20, 60],
    startingItems: ['divine_source_fragment', 'mining_tool', 'rough_clothes'],
    startingTechniques: ['source_sense'],
    startingMethodId: 'source_cultivation_method',
    startingTalentCount: 1,
    possibleZones: ['mines', 'stone_city'],
    socialConnections: ['mine_overseer', 'fellow_miner'],
    questCategories: ['mining', 'escape', 'opportunity'],
    startingPosition: '古矿奴',
  },
  {
    type: 'zhetian_terra_cotta',
    name: '兵马俑后人',
    description: '你的祖先是一位强大的兵马俑将领，血脉中流淌着战意。你天生适合战斗，体内沉睡着远古战魂的力量。',
    rarity: 'rare',
    worldId: WorldId.ZHE_TIAN,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [100, 300],
    startingItems: ['terra_cotta_armor', 'ancient_spear', 'war_banner'],
    startingTechniques: ['war_soul_awakening'],
    startingMethodId: 'terra_cotta_method',
    startingTalentCount: 2,
    possibleZones: ['ruins', 'stone_city'],
    socialConnections: ['war_spirit', 'ancient_general'],
    questCategories: ['war', 'bloodline', 'ancient'],
    startingPosition: '兵马俑后人',
  },
  {
    type: 'shengxu_evolutionary',
    name: '进化者',
    description: '你在末世的残酷环境中觉醒了进化能力，身体发生了异变。你拥有一种特殊能力，可以通过吞噬进化。',
    rarity: 'rare',
    worldId: WorldId.SHENG_XU,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 1,
    startingGold: [50, 150],
    startingItems: ['evolution_crystal', 'mutated_fruit', 'survival_kit'],
    startingTechniques: ['evolution_devour'],
    startingMethodId: 'evolution_method',
    startingTalentCount: 2,
    possibleZones: ['wasteland', 'stone_city'],
    socialConnections: ['evolutionary', 'mutant_beast'],
    questCategories: ['evolution', 'survival', 'power'],
    startingPosition: '进化者',
  },
  {
    type: 'shengxu_dao_seed',
    name: '道种',
    description: '你的体内被某位大能种下了一颗道种，这颗种子蕴含着那位大能的修炼感悟。随着你的成长，道种会逐渐发芽，带给你无穷的造化。',
    rarity: 'epic',
    worldId: WorldId.SHENG_XU,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 3,
    startingGold: [300, 800],
    startingItems: ['dao_seed', 'nurturing_pill', 'spirit_soil'],
    startingTechniques: ['dao_seed_communion'],
    startingMethodId: 'dao_seed_method',
    startingTalentCount: 3,
    possibleZones: ['divine_garden', 'immortal_mountain'],
    socialConnections: ['planter', 'dao_protector'],
    questCategories: ['dao', 'growth', 'legendary'],
    startingPosition: '道种拥有者',
  },
  {
    type: 'shenmu_undead',
    name: '不死生物',
    description: '你是从神魔陵园中爬出的不死生物，拥有不死不灭的特性。虽然失去了生前的记忆，但你获得了永恒的生命和强大的力量。',
    rarity: 'epic',
    worldId: WorldId.SHEN_MU,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 3,
    startingGold: [200, 600],
    startingItems: ['death_bone', 'soul_fire', 'undead_robe'],
    startingTechniques: ['undead_regeneration'],
    startingMethodId: 'undead_method',
    startingTalentCount: 3,
    possibleZones: ['shenmu_cemetery', 'burial_domain'],
    socialConnections: ['death_god', 'undead_king'],
    questCategories: ['undead', 'eternal', 'dark'],
    startingPosition: '不死生物',
  },
  {
    type: 'doupo_alchemist_genius',
    name: '炼药天才',
    description: '你是斗气大陆上罕见的炼药天才，对火焰有着超乎常人的掌控力。你的梦想是成为传说中的药帝，炼制出可起死回生的神丹。',
    rarity: 'epic',
    worldId: WorldId.DOU_PO,
    startingRealm: CultivationRealm.BLOOD_MOVING,
    startingStage: 2,
    startingGold: [300, 800],
    startingItems: ['heaven_flame_seed', 'alchemist_robe', 'pill_formula_collection'],
    startingTechniques: ['flame_control'],
    startingMethodId: 'alchemy_emperor_method',
    startingTalentCount: 3,
    possibleZones: ['doupo_wutan', 'stone_city'],
    socialConnections: ['alchemist_master', 'flame_spirit'],
    questCategories: ['alchemy', 'flame', 'legendary'],
    startingPosition: '炼药天才',
  },
];

export class OriginSystem {
  static generateOrigin(worldId?: WorldId): IOriginResult {
    const weights = this.calculateWeights(worldId);
    const config = this.selectByWeight(weights);
    const zone = this.selectZone(config);
    const room = this.selectRoom(zone, config.startingRoomId);

    return {
      config,
      zoneId: zone.id,
      roomId: room.id,
      zoneName: zone.name,
      roomName: room.name,
      originName: config.name,
      originDescription: config.description,
    };
  }

  static calculateWeights(worldId?: WorldId): { config: IOriginConfig; weight: number }[] {
    const rarityWeights: Record<string, number> = {
      common: 25,
      uncommon: 35,
      rare: 25,
      epic: 12,
      legendary: 3,
    };

    const filtered = worldId
      ? ORIGIN_CONFIGS.filter(c => c.worldId === worldId)
      : ORIGIN_CONFIGS;

    return filtered.map(config => ({
      config,
      weight: rarityWeights[config.rarity],
    }));
  }

  static selectByWeight(weighted: { config: IOriginConfig; weight: number }[]): IOriginConfig {
    const total = weighted.reduce((sum, w) => sum + w.weight, 0);
    let random = Math.random() * total;

    for (const { config, weight } of weighted) {
      random -= weight;
      if (random <= 0) return config;
    }

    return weighted[weighted.length - 1].config;
  }

  static selectZone(config: IOriginConfig) {
    const blueprints = ZoneBlueprintDB.getAll();
    const available = blueprints.filter(bp => config.possibleZones.includes(bp.id));

    if (available.length === 0) {
      const fallback = blueprints[Math.floor(Math.random() * blueprints.length)];
      return fallback || { id: 'unknown', name: '未知区域', rooms: [{ id: 'entrance', name: '入口' }] };
    }

    return available[Math.floor(Math.random() * available.length)];
  }

  static selectRoom(zone: any, preferredRoomId?: string) {
    if (!zone || !Array.isArray(zone.rooms) || zone.rooms.length === 0) {
      return { id: 'default_room', name: '默认房间' };
    }

    // 优先使用出身指定的起始房间
    if (preferredRoomId) {
      const preferred = zone.rooms.find((r: any) => r.id === preferredRoomId);
      if (preferred) return preferred;
    }

    const entranceRooms = zone.rooms.filter((r: any) => 
      r.exits?.some((e: any) => e.targetZoneId) || r.id?.includes('gate') || r.id?.includes('entrance')
    );

    if (entranceRooms.length > 0) {
      return entranceRooms[Math.floor(Math.random() * entranceRooms.length)];
    }

    return zone.rooms[0];
  }

  static createPlayerFromOrigin(origin: IOriginResult): Partial<IPlayer> {
    const config = origin.config;
    const gold = Math.floor(Math.random() * (config.startingGold[1] - config.startingGold[0] + 1)) + config.startingGold[0];

    const techniques = config.startingTechniques
      .map(id => getTechniqueById(id))
      .filter((t): t is any => t !== undefined);

    const inventory = config.startingItems.flatMap(itemId => {
      const item = getItemById(itemId);
      if (!item) return [];
      if (itemId.includes('_x')) {
        const [, count] = itemId.split('_x');
        return Array(parseInt(count) || 1).fill({ ...item });
      }
      return [{ ...item }];
    });

    let method = config.startingMethodId ? getMethod(config.startingMethodId) : undefined;
    // 功法数据不存在时回退到默认基础功法，避免"功法数据异常"
    let methodId = config.startingMethodId;
    if (config.startingMethodId && !method) {
      method = getMethod('yuanshi_zhenjie');
      methodId = method ? 'yuanshi_zhenjie' : undefined;
    }

    const fluctuation = 0.9 + Math.random() * 0.2;

    const baseHp = this.calculateBaseHp(config);
    const baseMana = this.calculateBaseMana(config);

    return {
      name: '',
      currentWorldId: config.worldId,
      worldTravelRecords: {
        [config.worldId]: {
          worldId: config.worldId,
          firstArrivalTime: 0,
          highestRealmLevel: config.startingRealm,
          totalTimeSpent: 0,
          ascended: false,
        },
      },
      realm: config.startingRealm,
      realmStage: config.startingStage,
      realmPerfection: false,
      cultivationExp: 0,
      maxCultivationExp: this.calculateMaxExp(config.startingRealm, config.startingStage),
      gold,
      techniques,
      inventory,
      currentMethodId: methodId,
      knownMethodIds: methodId ? [methodId] : [],
      methodProficiency: 0,
      methodMaxProficiency: method?.proficiencyRequired || 100,
      methodEnlightenmentCount: 0,
      currentRoomId: origin.roomId,
      currentZoneId: origin.zoneId,
      discoveredZones: [origin.zoneId],
      talentIds: [],
      passives: [],
      spiritAbsorbRate: (method?.speedBonus || 1.0) * fluctuation,
      attack: Math.floor(this.calculateBaseAttack(config) * fluctuation),
      defense: Math.floor(this.calculateBaseDefense(config) * fluctuation),
      speed: Math.floor(this.calculateBaseSpeed(config) * fluctuation),
      maxHp: Math.floor(baseHp * fluctuation),
      hp: Math.floor(baseHp * fluctuation),
      maxMana: Math.floor(baseMana * fluctuation),
      mana: Math.floor(baseMana * fluctuation),
      critRate: 0.03,
      position: config.startingPosition,
    };
  }

  static calculateMaxExp(realm: CultivationRealm, stage: number): number {
    return 30 * (realm + 1) * stage;
  }

  static calculateBaseAttack(config: IOriginConfig): number {
    const base = 5;
    const realmBonus = config.startingRealm * 3;
    const stageBonus = (config.startingStage - 1) * 2;
    return base + realmBonus + stageBonus;
  }

  static calculateBaseDefense(config: IOriginConfig): number {
    const base = 2;
    const realmBonus = config.startingRealm * 2;
    const stageBonus = (config.startingStage - 1) * 1;
    return base + realmBonus + stageBonus;
  }

  static calculateBaseSpeed(config: IOriginConfig): number {
    const base = 5;
    const realmBonus = config.startingRealm * 2;
    const stageBonus = (config.startingStage - 1) * 1;
    return base + realmBonus + stageBonus;
  }

  static calculateBaseHp(config: IOriginConfig): number {
    const base = 50;
    const realmBonus = config.startingRealm * 20;
    const stageBonus = (config.startingStage - 1) * 10;
    return base + realmBonus + stageBonus;
  }

  static calculateBaseMana(config: IOriginConfig): number {
    const base = 20;
    const realmBonus = config.startingRealm * 10;
    const stageBonus = (config.startingStage - 1) * 5;
    return base + realmBonus + stageBonus;
  }

  static getOriginConfig(type: OriginType): IOriginConfig | undefined {
    return ORIGIN_CONFIGS.find(c => c.type === type);
  }

  static getAllOrigins(): IOriginConfig[] {
    return ORIGIN_CONFIGS;
  }

  static getOriginsByWorld(worldId: WorldId): IOriginConfig[] {
    return ORIGIN_CONFIGS.filter(c => c.worldId === worldId);
  }

  static generateOrigins(worldId?: WorldId, count: number = 3): IOriginResult[] {
    const weights = this.calculateWeights(worldId);
    const results: IOriginResult[] = [];
    const usedConfigs = new Set<string>();

    for (let i = 0; i < count; i++) {
      const available = weights.filter(w => !usedConfigs.has(w.config.type));
      if (available.length === 0) break;

      const config = this.selectByWeight(available);
      usedConfigs.add(config.type);

      const zone = this.selectZone(config);
      const room = this.selectRoom(zone, config.startingRoomId);

      results.push({
        config,
        zoneId: zone.id,
        roomId: room.id,
        zoneName: zone.name,
        roomName: room.name,
        originName: config.name,
        originDescription: config.description,
      });
    }

    return results;
  }
}
